#!/usr/bin/env bash
# It script installs nginx in my server
# Nginx listens on port 80
# A GET returns a page that contains the string "Holberton School"

apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
