#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
hours=0
while [ $hours -lt 12 ]
do
    echo "Hour: $hours"
    mins=1
    while [ $mins -le 59 ]
    do
        echo $mins
        ((mins++))
    done
((hours++))
done
echo "Hour: $hours"
